/**
 * Centralized user-facing copy.
 */

const COMMON_LABELS = {
  appearance: 'Appearance',
  back: 'Back',
  cancel: 'Cancel',
  clear: 'Clear',
  close: 'Close',
  confirm: 'Confirm',
  continue: 'Continue',
  downloads: 'Downloads',
  home: 'Home',
  loading: 'Loading',
  login: 'Login',
  moreInfo: 'More Info',
  notAvailable: 'Not available',
  profile: 'Profile',
  retry: 'Retry',
  language: 'Language',
  logout: 'Logout',
  save: 'Save',
  search: 'Search',
  settings: 'Settings',
  signOut: 'Sign Out',
} as const;

export const APP_STRINGS = {
  common: {
    appName: 'House of Edtech',
    appearance: COMMON_LABELS.appearance,
    loading: COMMON_LABELS.loading,
    retry: COMMON_LABELS.retry,
    cancel: COMMON_LABELS.cancel,
    continue: COMMON_LABELS.continue,
    back: COMMON_LABELS.back,
    save: COMMON_LABELS.save,
    search: COMMON_LABELS.search,
    seeAll: 'See All',
    playNow: 'Play Now',
    moreInfo: COMMON_LABELS.moreInfo,
    addToWatchlist: 'Add to Watchlist',
    downloads: COMMON_LABELS.downloads,
    language: COMMON_LABELS.language,
    logout: COMMON_LABELS.logout,
    comingSoon: 'Coming Soon',
    notAvailable: COMMON_LABELS.notAvailable,
  },
  components: {
    activityIndicator: {
      accessibilityLabel: 'Loading indicator',
    },
    button: {
      loadingAccessibilityLabel: 'Action in progress',
      primaryAccessibilityHint: 'Activates this action.',
      secondaryAccessibilityHint: 'Activates this secondary action.',
      ghostAccessibilityHint: 'Activates this action.',
      textAccessibilityHint: 'Activates this text action.',
      iconAccessibilityHint: 'Activates this icon action.',
      chipAccessibilityHint: 'Toggles this chip option.',
      segmentAccessibilityHint: 'Selects this segment option.',
      floatingAccessibilityHint: 'Activates this quick action.',
    },
    cards: {
      categoryAccessibilityHint: 'Opens this category.',
      downloadAccessibilityHint: 'Opens this download item.',
      episodeAccessibilityHint: 'Opens this episode.',
      heroAccessibilityHint: 'Opens this featured item.',
      movieAccessibilityHint: 'Opens this title.',
      profileAccessibilityHint: 'Opens this profile item.',
      searchAccessibilityHint: 'Opens this search result.',
      settingsAccessibilityHint: 'Opens this setting.',
    },
    image: {
      accessibilityLabel: 'Image',
      loadingLabel: 'Loading image',
      errorLabel: 'Image unavailable',
    },
    loader: {
      infiniteLoadingLabel: 'Loading more content',
      noMoreContentLabel: 'No more content available',
      pullToRefreshLabel: 'Refresh content',
    },
    media: {
      avatarAccessibilityLabel: 'Profile avatar',
      avatarAccessibilityHint: 'Opens this avatar action.',
      itemAccessibilityHint: 'Opens this item.',
      labelValueRowAccessibilityHint: 'Opens this item.',
      posterAccessibilityLabel: 'Poster artwork',
      posterAccessibilityHint: 'Opens this title.',
      progressAccessibilityLabel: 'Playback progress',
      ratingAccessibilityLabel: 'Content rating',
      thumbnailAccessibilityLabel: 'Thumbnail artwork',
      thumbnailAccessibilityHint: 'Opens this media item.',
    },
    modal: {
      closeLabel: COMMON_LABELS.close,
      confirmLabel: COMMON_LABELS.confirm,
      dismissAccessibilityLabel: 'Dismiss modal',
      dismissAccessibilityHint: 'Dismisses this modal.',
    },
    navigation: {
      backButtonAccessibilityLabel: 'Go back',
      backButtonAccessibilityHint: 'Navigates to the previous screen.',
      bottomTabAccessibilityHint: 'Opens this section.',
      clearSearchAccessibilityLabel: 'Clear search query',
      clearSearchAccessibilityHint: 'Clears the current search query.',
      closeSheetAccessibilityLabel: 'Close bottom sheet',
      searchBarAccessibilityHint: 'Enter text to search content.',
      searchBarAccessibilityLabel: 'Search input',
      searchPlaceholder: COMMON_LABELS.search,
    },
    stateView: {
      emptyDescription: 'Content will appear here when available.',
      emptyTitle: 'Nothing here yet',
      loadingDescription: 'Please wait while content loads.',
      loadingTitle: COMMON_LABELS.loading,
    },
    offline: {
      illustrationAccessibilityLabel: 'Offline connection illustration',
      retryAccessibilityHint: 'Checks your internet connection again.',
      retryAccessibilityLabel: 'Retry internet connection',
    },
    toast: {
      dismissAccessibilityHint: 'Dismisses this notification.',
      dismissAccessibilityLabel: 'Dismiss notification',
      notificationAccessibilityLabel: 'In-app notification',
    },
    video: {
      accessibilityLabel: 'Video player',
      loadingLabel: 'Loading video',
      errorLabel: 'Video unavailable',
    },
    textInput: {
      accessibilityLabel: 'Text input',
      secureToggleHint: 'Toggles secure text visibility.',
      showSecureEntry: 'Show',
      hideSecureEntry: 'Hide',
      characterCounterAccessibilityLabel: 'Character count',
    },
  },
  navigation: {
    splash: 'Splash',
    login: COMMON_LABELS.login,
    home: COMMON_LABELS.home,
    search: COMMON_LABELS.search,
    downloads: COMMON_LABELS.downloads,
    profile: COMMON_LABELS.profile,
    movieDetails: 'Movie Details',
    settings: COMMON_LABELS.settings,
  },
  auth: {
    title: 'Welcome back',
    subtitle: 'Sign in to continue streaming your watchlist.',
    emailLabel: 'Email address',
    passwordLabel: 'Password',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    otpTitle: 'Verify your account',
  },
  splash: {
    imageAccessibilityLabel: 'House of Edtech splash artwork',
    loadingMessage: 'Preparing your streaming experience.',
  },
  home: {
    categoriesSection: 'Popular Categories',
    categoriesEmptyDescription: 'Categories are unavailable right now.',
    categoriesErrorDescription: 'We could not load movie categories. Try again.',
    categoriesErrorTitle: 'Categories unavailable',
    headerTitle: 'AURA',
    genreEmptyDescription: 'Try another category to explore more titles.',
    genreEmptyTitle: 'No titles for this category',
    heroTitle: 'Premiere',
    hoursShort: 'h',
    menuAccessibilityHint: 'Navigates to settings.',
    menuAccessibilityLabel: 'Open settings',
    metadataSeparator: ' • ',
    minutesLeftSuffix: 'left',
    minutesShort: 'm',
    nowPlayingSection: 'Now Playing',
    nowPlayingSectionDescription: 'Fresh theatrical releases available right now.',
    popularMoviesSection: 'Popular Movies',
    popularMoviesSectionDescription: 'The broadest audience favorites across the catalog.',
    profileAccessibilityHint: 'Opens your profile.',
    ratingSourceLabel: 'TMDB',
    sectionActionAccessibilityHint: 'Opens the full list for this section.',
    topRatedSection: 'Top Rated',
    topRatedSectionDescription: 'Critically loved titles with strong audience approval.',
    trendingMoviesSection: 'Trending Movies',
    trendingMoviesSectionDescription: 'What viewers are discovering and talking about today.',
    upcomingSection: 'Upcoming',
    upcomingSectionDescription: 'Movies releasing soon so your watchlist stays ahead.',
    trendingSection: 'Trending Now',
    continueWatchingSection: 'Continue Watching',
    recommendedSection: 'Recommended For You',
    newReleasesSection: 'New Releases',
  },
  details: {
    addToFavoritesAccessibilityHint: 'Adds this title to favorites.',
    addToFavoritesAccessibilityLabel: 'Add to favorites',
    budgetLabel: 'Budget',
    castEmptyDescription: 'Cast details will appear here when available.',
    castEmptyTitle: 'Cast unavailable',
    castSection: 'Cast',
    castTab: 'Cast',
    crewSection: 'Crew',
    detailsTab: 'Details',
    downloadAction: 'Download',
    trailersSection: 'Trailers',
    trailerAction: 'Watch Trailer',
    trailerEmptyDescription: 'A trailer is not available for this title yet.',
    trailerEmptyTitle: 'Trailer unavailable',
    trailerSection: 'Trailer',
    recommendationsSection: 'More Like This',
    recommendedEmptyDescription: 'Recommendations will appear here when available.',
    recommendedEmptyTitle: 'No recommendations yet',
    recommendedTab: 'Recommended',
    episodesSection: 'Episodes',
    galleryEmptyDescription: 'Images will appear here when available.',
    galleryEmptyTitle: 'Gallery unavailable',
    gallerySection: 'Gallery',
    galleryTab: 'Gallery',
    genresLabel: 'Genres',
    informationSection: 'Movie Info',
    languageLabel: 'Language',
    movieBadge: 'Movie',
    overviewReadLess: 'Read Less',
    overviewReadMore: 'Read More',
    playAction: 'Play',
    playTrailerAction: 'Play Trailer',
    productionCompaniesLabel: 'Production Companies',
    ratingOutOfTenSuffix: '/10',
    releaseDateLabel: 'Release Date',
    removeFromFavoritesAccessibilityHint: 'Removes this title from favorites.',
    removeFromFavoritesAccessibilityLabel: 'Remove from favorites',
    revenueLabel: 'Revenue',
    runtimeLabel: 'Runtime',
    seasonsLabel: 'Seasons',
    shareAccessibilityHint: 'Shares this title.',
    shareAccessibilityLabel: 'Share title',
    similarEmptyDescription: 'Similar titles will appear here when available.',
    similarEmptyTitle: 'No similar titles yet',
    similarSection: 'Similar Movies',
    similarTab: 'Similar',
    statusLabel: 'Status',
    synopsisSection: 'Synopsis',
    yearAndMetadataSeparator: ' • ',
  },
  search: {
    categoriesEmptyDescription: 'Categories are unavailable right now.',
    categoriesSection: 'Categories',
    discoveryErrorDescription: 'We could not load search discovery right now.',
    discoveryErrorTitle: 'Search unavailable',
    headerTitle: 'AURA',
    menuAccessibilityHint: 'Opens settings.',
    menuAccessibilityLabel: 'Open settings',
    popularTalentEmptyDescription: 'Popular talent will appear here when available.',
    popularTalentSection: 'Popular Talent',
    profileAccessibilityHint: 'Opens your profile.',
    profileAccessibilityLabel: 'Open profile',
    placeholder: 'Movies, Shows, Actors...',
    recentSearches: 'Recent Searches',
    recommendedBadge: 'Must Watch',
    recommendedEmptyDescription: 'Recommendations will appear here when available.',
    recommendedRailTitle: 'Recommended Movies',
    recommendedSection: 'Recommended for You',
    trendingSearches: 'Trending Searches',
    trendingSearchesEmptyDescription: 'Trending searches are unavailable right now.',
    trendingSearchesSectionActionLabel: 'Trending insights',
    suggestions: 'Suggestions',
    emptyStateTitle: 'No matches found',
    emptyStateDescription: 'Try another title, genre, or keyword.',
    voiceSearchAccessibilityHint: 'Starts voice search when supported.',
    voiceSearchAccessibilityLabel: 'Voice search',
  },
  downloads: {
    title: 'Offline Downloads',
    storageSection: 'Storage',
    qualitySection: 'Download Quality',
    emptyStateTitle: 'No downloads yet',
    emptyStateDescription: 'Downloaded titles will appear here for offline playback.',
    deleteSuccessMessage: 'Download removed from your device.',
  },
  offline: {
    title: 'You are offline',
    description:
      'Reconnect to keep browsing movies, recommendations, and streaming updates.',
    retryAction: 'Try Again',
  },
  profile: {
    accountSection: 'Account',
    appearanceDark: 'Dark',
    appearanceLight: 'Light',
    appearanceSectionTitle: COMMON_LABELS.appearance,
    appearanceValueLabel: 'Theme',
    appFooterSuffix: 'BUILT FOR CINEMA',
    appFooterTitle: 'AURA STREAM',
    badgeLabel: 'PREMIUM MEMBER',
    downloadsAccessibilityHint: 'Opens your downloaded titles.',
    downloadsStoredLocallySuffix: 'stored locally',
    downloadsStorageValueSuffix: 'GB',
    emptyStateDescription:
      'Profile details will appear here when your account data is available.',
    emptyStateTitle: 'Profile unavailable',
    footerDivider: '•',
    headerAvatarAccessibilityHint: 'Opens your profile details.',
    headerAvatarAccessibilityLabel: 'Current profile avatar',
    headerTitle: 'AURA',
    languageAccessibilityHint: 'Opens language preferences.',
    languageSectionTitle: COMMON_LABELS.language,
    logoutAccessibilityHint: 'Signs out of the app.',
    logoutButtonLabel: COMMON_LABELS.logout,
    manageAccessibilityHint: 'Opens membership management.',
    manageButtonLabel: 'Manage',
    membershipDescription:
      'Unlimited 4K streaming, offline downloads, and early access.',
    membershipIconAccessibilityLabel: 'Membership badge',
    membershipTitle: 'Aura Premium',
    menuAccessibilityHint: 'Opens the app settings screen.',
    menuAccessibilityLabel: 'Open app menu',
    notificationsEnabledLabel: 'Enabled',
    notificationsAccessibilityHint: 'Opens notification preferences.',
    notificationsLabel: 'Notifications',
    premiumRenewsPrefix: 'Renews',
    profileAvatarAccessibilityLabel: 'Profile avatar',
    profileAvatarAccessibilityHint: 'Shows the current profile image.',
    themeDarkAccessibilityHint: 'Switches the app to dark appearance.',
    themeDarkAccessibilityLabel: 'Use dark theme',
    themeLightAccessibilityHint: 'Switches the app to light appearance.',
    themeLightAccessibilityLabel: 'Use light theme',
    themeToggleAccessibilityLabel: 'Theme appearance switcher',
    watchingGroupLabel: 'Watching',
    watchHistoryAccessibilityHint: 'Opens your watch history.',
    watchHistoryLabel: 'Watch History',
    watchHistorySubtitle: 'Recently watched',
    watchHistorySection: 'Watch History',
    preferencesGroupLabel: 'Preferences',
    preferencesSection: 'Preferences',
    subscriptionSection: 'Subscription',
    signOut: COMMON_LABELS.signOut,
  },
  settings: {
    appearanceSection: 'Appearance',
    backToHome: 'Back to Home',
    comingSoonDescription:
      "We're still working on this feature. It will be available in a future update.",
    comingSoonSubtitle: 'This feature is coming soon.',
    notificationsSection: 'Notifications',
    playbackSection: 'Playback',
    downloadsSection: 'Downloads',
    goBack: 'Go Back',
    languageSection: 'Language',
    privacySection: 'Privacy',
    placeholderTitle: COMMON_LABELS.settings,
    languageUpdatedSuccess: 'Language preference updated.',
    themeUpdatedSuccess: 'Theme preference updated.',
  },
  toast: {
    successTitle: 'Success',
    errorTitle: 'Something went wrong',
    warningTitle: 'Attention needed',
    infoTitle: 'FYI',
  },
  errors: {
    configurationTitle: 'Setup Required',
    genericTitle: 'Something went wrong',
    genericDescription: 'Please try again in a moment.',
    networkTitle: 'Connection issue',
    networkDescription: 'Check your internet connection and try again.',
    serverTitle: 'Service unavailable',
    serverDescription: 'The service is temporarily unavailable.',
    timeoutTitle: 'Request timed out',
    timeoutDescription: 'The request took too long. Please try again.',
    unauthorizedTitle: 'Authorization issue',
    unauthorizedDescription: 'Your session could not be verified.',
    tmdbConfigurationDescription:
      'Set EXPO_PUBLIC_TMDB_ACCESS_TOKEN or EXPO_PUBLIC_TMDB_API_KEY to load the Home catalog.',
  },
} as const;
