/**
 * Centralized user-facing copy.
 */

const COMMON_LABELS = {
  back: 'Back',
  cancel: 'Cancel',
  clear: 'Clear',
  close: 'Close',
  confirm: 'Confirm',
  continue: 'Continue',
  downloads: 'Downloads',
  home: 'Home',
  loading: 'Loading',
  login: 'Login',
  moreInfo: 'More Info',
  notAvailable: 'Not available',
  profile: 'Profile',
  retry: 'Retry',
  save: 'Save',
  search: 'Search',
  settings: 'Settings',
  signOut: 'Sign Out',
} as const;

export const APP_STRINGS = {
  common: {
    appName: 'House of Edtech',
    loading: COMMON_LABELS.loading,
    retry: COMMON_LABELS.retry,
    cancel: COMMON_LABELS.cancel,
    continue: COMMON_LABELS.continue,
    back: COMMON_LABELS.back,
    save: COMMON_LABELS.save,
    search: COMMON_LABELS.search,
    seeAll: 'See All',
    playNow: 'Play Now',
    moreInfo: COMMON_LABELS.moreInfo,
    addToWatchlist: 'Add to Watchlist',
    downloads: COMMON_LABELS.downloads,
    comingSoon: 'Coming Soon',
    notAvailable: COMMON_LABELS.notAvailable,
  },
  components: {
    activityIndicator: {
      accessibilityLabel: 'Loading indicator',
    },
    button: {
      loadingAccessibilityLabel: 'Action in progress',
      primaryAccessibilityHint: 'Activates this action.',
      secondaryAccessibilityHint: 'Activates this secondary action.',
      ghostAccessibilityHint: 'Activates this action.',
      textAccessibilityHint: 'Activates this text action.',
      iconAccessibilityHint: 'Activates this icon action.',
      chipAccessibilityHint: 'Toggles this chip option.',
      segmentAccessibilityHint: 'Selects this segment option.',
      floatingAccessibilityHint: 'Activates this quick action.',
    },
    cards: {
      categoryAccessibilityHint: 'Opens this category.',
      downloadAccessibilityHint: 'Opens this download item.',
      episodeAccessibilityHint: 'Opens this episode.',
      heroAccessibilityHint: 'Opens this featured item.',
      movieAccessibilityHint: 'Opens this title.',
      profileAccessibilityHint: 'Opens this profile item.',
      searchAccessibilityHint: 'Opens this search result.',
      settingsAccessibilityHint: 'Opens this setting.',
    },
    image: {
      accessibilityLabel: 'Image',
      loadingLabel: 'Loading image',
      errorLabel: 'Image unavailable',
    },
    loader: {
      infiniteLoadingLabel: 'Loading more content',
      noMoreContentLabel: 'No more content available',
      pullToRefreshLabel: 'Refresh content',
    },
    media: {
      avatarAccessibilityLabel: 'Profile avatar',
      avatarAccessibilityHint: 'Opens this avatar action.',
      itemAccessibilityHint: 'Opens this item.',
      labelValueRowAccessibilityHint: 'Opens this item.',
      posterAccessibilityLabel: 'Poster artwork',
      posterAccessibilityHint: 'Opens this title.',
      progressAccessibilityLabel: 'Playback progress',
      ratingAccessibilityLabel: 'Content rating',
      thumbnailAccessibilityLabel: 'Thumbnail artwork',
      thumbnailAccessibilityHint: 'Opens this media item.',
    },
    modal: {
      closeLabel: COMMON_LABELS.close,
      confirmLabel: COMMON_LABELS.confirm,
      dismissAccessibilityLabel: 'Dismiss modal',
      dismissAccessibilityHint: 'Dismisses this modal.',
    },
    navigation: {
      backButtonAccessibilityLabel: 'Go back',
      backButtonAccessibilityHint: 'Navigates to the previous screen.',
      bottomTabAccessibilityHint: 'Opens this section.',
      clearSearchAccessibilityLabel: 'Clear search query',
      clearSearchAccessibilityHint: 'Clears the current search query.',
      closeSheetAccessibilityLabel: 'Close bottom sheet',
      searchBarAccessibilityHint: 'Enter text to search content.',
      searchBarAccessibilityLabel: 'Search input',
      searchPlaceholder: COMMON_LABELS.search,
    },
    stateView: {
      emptyDescription: 'Content will appear here when available.',
      emptyTitle: 'Nothing here yet',
      loadingDescription: 'Please wait while content loads.',
      loadingTitle: COMMON_LABELS.loading,
    },
    video: {
      accessibilityLabel: 'Video player',
      loadingLabel: 'Loading video',
      errorLabel: 'Video unavailable',
    },
    textInput: {
      accessibilityLabel: 'Text input',
      secureToggleHint: 'Toggles secure text visibility.',
      showSecureEntry: 'Show',
      hideSecureEntry: 'Hide',
      characterCounterAccessibilityLabel: 'Character count',
    },
  },
  navigation: {
    splash: 'Splash',
    login: COMMON_LABELS.login,
    home: COMMON_LABELS.home,
    search: COMMON_LABELS.search,
    downloads: COMMON_LABELS.downloads,
    profile: COMMON_LABELS.profile,
    movieDetails: 'Movie Details',
    settings: COMMON_LABELS.settings,
  },
  auth: {
    title: 'Welcome back',
    subtitle: 'Sign in to continue streaming your watchlist.',
    emailLabel: 'Email address',
    passwordLabel: 'Password',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    otpTitle: 'Verify your account',
  },
  splash: {
    imageAccessibilityLabel: 'House of Edtech splash artwork',
    loadingMessage: 'Preparing your streaming experience.',
  },
  home: {
    categoriesSection: 'Popular Categories',
    categoriesEmptyDescription: 'Categories are unavailable right now.',
    categoriesErrorDescription: 'We could not load movie categories. Try again.',
    categoriesErrorTitle: 'Categories unavailable',
    headerTitle: 'AURA',
    genreEmptyDescription: 'Try another category to explore more titles.',
    genreEmptyTitle: 'No titles for this category',
    heroTitle: 'Premiere',
    hoursShort: 'h',
    menuAccessibilityHint: 'Navigates to settings.',
    menuAccessibilityLabel: 'Open settings',
    metadataSeparator: ' • ',
    minutesLeftSuffix: 'left',
    minutesShort: 'm',
    nowPlayingSection: 'Now Playing',
    nowPlayingSectionDescription: 'Fresh theatrical releases available right now.',
    popularMoviesSection: 'Popular Movies',
    popularMoviesSectionDescription: 'The broadest audience favorites across the catalog.',
    profileAccessibilityHint: 'Opens your profile.',
    ratingSourceLabel: 'TMDB',
    sectionActionAccessibilityHint: 'Opens the full list for this section.',
    topRatedSection: 'Top Rated',
    topRatedSectionDescription: 'Critically loved titles with strong audience approval.',
    trendingMoviesSection: 'Trending Movies',
    trendingMoviesSectionDescription: 'What viewers are discovering and talking about today.',
    upcomingSection: 'Upcoming',
    upcomingSectionDescription: 'Movies releasing soon so your watchlist stays ahead.',
    trendingSection: 'Trending Now',
    continueWatchingSection: 'Continue Watching',
    recommendedSection: 'Recommended For You',
    newReleasesSection: 'New Releases',
  },
  details: {
    addToFavoritesAccessibilityHint: 'Adds this title to favorites.',
    addToFavoritesAccessibilityLabel: 'Add to favorites',
    budgetLabel: 'Budget',
    castEmptyDescription: 'Cast details will appear here when available.',
    castEmptyTitle: 'Cast unavailable',
    castSection: 'Cast',
    castTab: 'Cast',
    crewSection: 'Crew',
    detailsTab: 'Details',
    downloadAction: 'Download',
    trailersSection: 'Trailers',
    trailerAction: 'Watch Trailer',
    trailerEmptyDescription: 'A trailer is not available for this title yet.',
    trailerEmptyTitle: 'Trailer unavailable',
    trailerSection: 'Trailer',
    recommendationsSection: 'More Like This',
    recommendedEmptyDescription: 'Recommendations will appear here when available.',
    recommendedEmptyTitle: 'No recommendations yet',
    recommendedTab: 'Recommended',
    episodesSection: 'Episodes',
    galleryEmptyDescription: 'Images will appear here when available.',
    galleryEmptyTitle: 'Gallery unavailable',
    gallerySection: 'Gallery',
    galleryTab: 'Gallery',
    genresLabel: 'Genres',
    informationSection: 'Movie Info',
    languageLabel: 'Language',
    movieBadge: 'Movie',
    overviewReadLess: 'Read Less',
    overviewReadMore: 'Read More',
    playAction: 'Play',
    playTrailerAction: 'Play Trailer',
    productionCompaniesLabel: 'Production Companies',
    ratingOutOfTenSuffix: '/10',
    releaseDateLabel: 'Release Date',
    removeFromFavoritesAccessibilityHint: 'Removes this title from favorites.',
    removeFromFavoritesAccessibilityLabel: 'Remove from favorites',
    revenueLabel: 'Revenue',
    runtimeLabel: 'Runtime',
    seasonsLabel: 'Seasons',
    shareAccessibilityHint: 'Shares this title.',
    shareAccessibilityLabel: 'Share title',
    similarEmptyDescription: 'Similar titles will appear here when available.',
    similarEmptyTitle: 'No similar titles yet',
    similarSection: 'Similar Movies',
    similarTab: 'Similar',
    statusLabel: 'Status',
    synopsisSection: 'Synopsis',
    yearAndMetadataSeparator: ' • ',
  },
  search: {
    placeholder: 'Search movies, series, and episodes',
    recentSearches: 'Recent Searches',
    trendingSearches: 'Trending Searches',
    suggestions: 'Suggestions',
    emptyStateTitle: 'No matches found',
    emptyStateDescription: 'Try another title, genre, or keyword.',
  },
  downloads: {
    title: 'Offline Downloads',
    storageSection: 'Storage',
    qualitySection: 'Download Quality',
    emptyStateTitle: 'No downloads yet',
    emptyStateDescription: 'Downloaded titles will appear here for offline playback.',
  },
  profile: {
    accountSection: 'Account',
    watchHistorySection: 'Watch History',
    preferencesSection: 'Preferences',
    subscriptionSection: 'Subscription',
    signOut: COMMON_LABELS.signOut,
  },
  settings: {
    appearanceSection: 'Appearance',
    notificationsSection: 'Notifications',
    playbackSection: 'Playback',
    downloadsSection: 'Downloads',
    languageSection: 'Language',
    privacySection: 'Privacy',
  },
  errors: {
    configurationTitle: 'Setup Required',
    genericTitle: 'Something went wrong',
    genericDescription: 'Please try again in a moment.',
    networkTitle: 'Connection issue',
    networkDescription: 'Check your internet connection and try again.',
    tmdbConfigurationDescription:
      'Set EXPO_PUBLIC_TMDB_ACCESS_TOKEN or EXPO_PUBLIC_TMDB_API_KEY to load the Home catalog.',
  },
} as const;
