/**
 * Light-mode color tokens extracted from DESIGN.md.
 *
 * A small number of semantic aliases reuse documented source values so the app
 * can consume consistent names without inventing new palette entries.
 */

import type { ThemeColors } from '../types';

export const lightColors = {
  background: '#faf8ff',
  surface: '#faf8ff',
  surfaceDim: '#d9d9e5',
  surfaceBright: '#faf8ff',
  surfaceLowest: '#ffffff',
  surfaceLow: '#f3f3fe',
  surfaceSecondary: '#ededf9',
  surfaceHigh: '#e7e7f3',
  surfaceHighest: '#e1e2ed',
  surfaceVariant: '#e1e2ed',
  card: '#ffffff',
  primary: '#004ac6',
  onPrimary: '#ffffff',
  primaryContainer: '#2563eb',
  onPrimaryContainer: '#eeefff',
  primaryFixed: '#dbe1ff',
  primaryFixedDim: '#b4c5ff',
  onPrimaryFixed: '#00174b',
  onPrimaryFixedVariant: '#003ea8',
  secondary: '#495c95',
  onSecondary: '#ffffff',
  secondaryContainer: '#acbfff',
  onSecondaryContainer: '#394c84',
  secondaryFixed: '#dbe1ff',
  secondaryFixedDim: '#b4c5ff',
  onSecondaryFixed: '#00174b',
  onSecondaryFixedVariant: '#31447b',
  tertiary: '#943700',
  onTertiary: '#ffffff',
  tertiaryContainer: '#bc4800',
  onTertiaryContainer: '#ffede6',
  tertiaryFixed: '#ffdbcd',
  tertiaryFixedDim: '#ffb596',
  onTertiaryFixed: '#360f00',
  onTertiaryFixedVariant: '#7d2d00',
  accent: '#2563eb',
  success: '#495c95',
  successContainer: '#acbfff',
  onSuccess: '#ffffff',
  warning: '#943700',
  warningContainer: '#bc4800',
  onWarning: '#ffffff',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onError: '#ffffff',
  info: '#004ac6',
  infoContainer: '#2563eb',
  onInfo: '#ffffff',
  inverseSurface: '#2e3039',
  inversePrimary: '#b4c5ff',
  border: '#737686',
  divider: '#c3c6d7',
  overlay: 'rgba(25, 27, 35, 0.56)',
  shadow: '#191b23',
  glassOverlay: 'rgba(255, 255, 255, 0.8)',
  heroOverlay: 'rgba(25, 27, 35, 0.15)',
  textPrimary: '#191b23',
  textSecondary: '#434655',
  textTertiary: '#737686',
  textInverse: '#f0f0fb',
  iconPrimary: '#191b23',
  iconSecondary: '#434655',
  navigationBackground: 'rgba(255, 255, 255, 0.8)',
  surfaceTint: '#0053db',
  white: '#ffffff',
  black: '#000000',
  transparent: 'transparent',
} as const satisfies ThemeColors;
